# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_max <- function(quantities, m, n) {
    .Call('_DIAgui_col_max', PACKAGE = 'DIAgui', quantities, m, n)
}

maxlfq_solve <- function(quantities, peptides, samples, margin = -10.0001) {
    .Call('_DIAgui_maxlfq_solve', PACKAGE = 'DIAgui', quantities, peptides, samples, margin)
}

